export const useVariebleStore = defineStore("variebleStore", () => {
  return {
    list: ref({
      admin: [
        {
          icon: "controls",
          id: 1,
          name: "menu1",
          path: "/cabinet/admin/control",
          title: "Управление",
        },
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/admin/department",
          title: "Отделы",
        },
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/admin/job",
          title: "Должность",
        },
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/admin/statement-type",
          title: "Тип заявления",
        },
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/admin/order-type",
          title: "Тип заказа",
        },
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/admin/statements",
          title: "Заявления",
        },
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/admin/orders",
          title: "Приказы",
        },
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/admin/task",
          title: "Задачи",
        },
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/admin/document",
          title: "Документы",
        },
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/admin/feed-list",
          title: "Новости",
        },
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/admin/chats",
          title: "Чаты",
        },
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/admin/folder/root",
          title: "Папки",
        },
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/admin/calendar",
          title: "Календарь",
        },
      ],
      confirmer: [
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/confirmer/statements/list",
          title: "Заявления",
        },
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/confirmer/orders",
          title: "Приказы",
        },
      ],
      creator: [
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/creator/statements/list/pending",
          title: "Заявления",
        },
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/creator/order",
          title: "Приказы",
        },
      ],
      employee: [
        {
          icon: "users",
          id: 1,
          name: "menu1",
          path: "/cabinet/employee/statements",
          title: "Заявления",
        },
      ],
    }),
    priority: ["default", "low", "medium", "high"],
    report_types: {
      daily_progress: "Ежедневный отчет по прогрессу",
      daily_report: "Сварочный отчет",
      electricity: "Ежедневный отчет Электрика",
      shift_report: "Ежедневный сменный рапорт",
      smr: "Ежедневный отчет СМР",
    },
    roles: {
      admin: "Технический администратор",
      confirmer: "Мастер",
      creator: "Создатель",
      employee: "Сотрудник",
    },
    unit_types: ["M", "M²", "M³", "ШТ", "ЧЕЛ", "Т", "ММ"],
  };
});
